### ISSUE TITLE
[Question]: How to solve CUDA error when building vector store?

### ISSUE THREAD

**Issue by zestaken** [run-llama/llama_index#10449]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When I build Index using faiss vector store, I get the following error telling me that something is wrong with CUDA, what could be the cause of this problem? What is the possible cause of this problem and how can I solve it? My code is:
```python
def getSeviceContext(embed_model, llm=None):
    """设置llm和embed_model"""
    from llama_index import ServiceContext
    # service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)
    # from llama_index.node_parser import SimpleNodeParser
    # parser = SimpleNodeParser
    service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)
    return service_context

def batch_generator(my_list, batch_size):
    for i in range(0, len(my_list), batch_size):
        yield my_list[i:i + batch_size]

# 构建Faiss vector store
def buildFaissVectorStore(embed_model,documents,index_path='./storage/',dimensions = 768):
    """构建Faiss vector store"""
    from llama_index import (
    load_index_from_storage,
    VectorStoreIndex,
    StorageContext
    )
    from llama_index.vector_stores.faiss import FaissVectorStore
    import faiss
    import os.path
    import torch 
    
    #构建Faiss索引模板
    d = dimensions # BioLORD模型生成的embedding的维度
    # faiss_index = faiss.IndexFlatL2(d) 
    faiss_index = faiss.IndexFlatIP(d) # 改为使用余弦相似度（内积）
    vector_store = FaissVectorStore(faiss_index=faiss_index)
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    service_context = getSeviceContext(embed_model)
    #如果本地存储了index则直接导入，否则重新生成并保存
    if not os.path.exists(index_path):
        #构建向量index
        batch_size = 3000
        for batch in batch_generator(documents, batch_size):
            index = VectorStoreIndex.from_documents(
                batch, storage_context=storage_context,service_context=service_context,show_progress=True
            )
    # index = VectorStoreIndex.build_index_from_nodes(nodes=documents, storage_context=storage_context,service_context=service_context)
            index.storage_context.persist(index_path)
            torch.cuda.empty_cache()        
    else:
        vector_store = FaissVectorStore.from_persist_dir(index_path)
        storage_context = StorageContext.from_defaults(
            vector_store=vector_store, persist_dir=index_path
        )
        index = load_index_from_storage(storage_context=storage_context,service_context=service_context)

    return index
index = buildFaissVectorStore(embed_model=embed_model, documents=c_doc)
```
The error is reported as follows：
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], [line 40](vscode-notebook-cell:?execution_count=4&line=40)
     [37](vscode-notebook-cell:?execution_count=4&line=37)         index = load_index_from_storage(storage_context=storage_context,service_context=service_context)
     [39](vscode-notebook-cell:?execution_count=4&line=39)     return index
---> [40](vscode-notebook-cell:?execution_count=4&line=40) index = buildFaissVectorStore(embed_model=embed_model, documents=c_doc)

Cell In[4], [line 26](vscode-notebook-cell:?execution_count=4&line=26)
     [24](vscode-notebook-cell:?execution_count=4&line=24)     batch_size = 3000
     [25](vscode-notebook-cell:?execution_count=4&line=25)     for batch in batch_generator(documents, batch_size):
---> [26](vscode-notebook-cell:?execution_count=4&line=26)         index = VectorStoreIndex.from_documents(
     [27](vscode-notebook-cell:?execution_count=4&line=27)             batch, storage_context=storage_context,service_context=service_context,show_progress=True
     [28](vscode-notebook-cell:?execution_count=4&line=28)         )
     [29](vscode-notebook-cell:?execution_count=4&line=29) # index = VectorStoreIndex.build_index_from_nodes(nodes=documents, storage_context=storage_context,service_context=service_context)
     [30](vscode-notebook-cell:?execution_count=4&line=30)         index.storage_context.persist(index_path)

File [~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:107](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:107), in BaseIndex.from_documents(cls, documents, storage_context, service_context, show_progress, **kwargs)
     [98](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:98)     docstore.set_document_hash(doc.get_doc_id(), doc.hash)
    [100](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:100) nodes = run_transformations(
    [101](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:101)     documents,  # type: ignore
    [102](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:102)     service_context.transformations,
    [103](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:103)     show_progress=show_progress,
    [104](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:104)     **kwargs,
    [105](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:105) )
--> [107](https://vscode-remote+ssh-002dremote-002b101-002e230-002e251-002e222.vscode-resource.vscode-cdn.net/home/jiezhang/NLP/~/.conda/envs/JieZhang/lib/python3.10/site-packages/llama_index/indices/base.py:107) return cls(
...
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
![image](https://github.com/run-llama/llama_index/assets/57577937/ab132fe2-2b54-4deb-9d96-ea004a9c8299)

**Comment by zestaken** [comment]
By what method can you solve the problem of oversized datasets when building a Vector store?

**Comment by logan-markewich** [comment]
what embed model are you using? If its roberta-based and uses `HuggingFaceEmbedding`, you might have to add `max_length=512` to the constructor

**Comment by zestaken** [comment]
> what embed model are you using? If its roberta-based and uses `HuggingFaceEmbedding`, you might have to add `max_length=512` to the constructor
@logan-markewich Thank you! I've set the max_length=512 and I'm still experiencing the same problem, so I'm not sure what the real reason for this error is?

**Comment by logan-markewich** [comment]
@zestaken can you share the code for setting up your embed_model?

**Comment by zestaken** [comment]
Thanks, I just solved this error by setting `max_length=256`!
