### ISSUE TITLE
[Question]: How to use VectorStoreIndex with French HuggingFace Embedding ?

### ISSUE THREAD

**Issue by mahmoudben96** [run-llama/llama_index#8837]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello Guys,

I am working on a RAG project and I encountered a problem while trying to use embeddings from HuggingFace in llama-index and I was hoping that someone could help me please.
I tried multiple embeddings in **French/Multilanguages** from HuggingFace and they do not work (eg : https://huggingface.co/antoinelouis/biencoder-camembert-base-mmarcoFR). The only that works for me is the english BAAI-bge family.

I used the code below :

```
from llama_index.finetuning import EmbeddingQAFinetuneDataset

dataset = EmbeddingQAFinetuneDataset("path_to_dataset")

corpus = dataset.corpus
nodes = [TextNode(id_=id_, text=text) for id_, text in corpus.items()]

from llama_index

from llama_index import ServiceContext, VectorStoreIndex, Simple
from llama_index.embeddings import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding("local_path_to_model")
service_context = ServiceContext.from_defaults(embed_model=embed_model)

index = VectorStoreIndex(nodes, service_context=service_context, show_progress=True)
```
The last line crashes and gives me the error :
```
CUDA error : CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```
When I tried to use the CPU, I get another error 
```
IndexError : index out of range in self
```

Here are some specs :
- OS : Linux
- GPU : Nvidia A100 80GB of VRAM
- CUDA version : 11.8 (I am unable to change this because I am not the admin on this machine).
- torch version : 2.0.1 (To my knowledge, it's the latest one that works with this version of CUDA).
- python version : 3.10.6
- llama-index version : 0.8.65

PS : This Embedding to create a RAG works just fine in langchain
PS-2 : A coworker told me that the model I tried to use doesn't have a pooling. When used via sentence-transformers (hence langchain), a mean pooling is generated. HuggingFaceEmbedding from llama_index.embeddings might not generate the pooling.

Thank you very much for you help,
Kind regards,
Mahmoud

**Comment by mahmoudben96** [comment]
@dosu-bot thanks for your quick answer. However, it is not relevant.

Indeed, PyTorch 2.0.1 does exist now. The latest version being 2.1.0 but I cannot installed (my NVIDIA driver version is 11.8 and I cannot upgrade it to >=12.0 because I do not have the admin right on the machine I work on).

Could you please try to give me another answer ?

Many thanks

**Comment by logan-markewich** [comment]
Hmmm this worked for me, at least on CPU

```
>>> from llama_index import ServiceContext, VectorStoreIndex
>>> from llama_index.embeddings import HuggingFaceEmbedding
>>> embed_model = HuggingFaceEmbedding(model_name="antoinelouis/biencoder-camembert-base-mmarcoFR")
>>> service_context = ServiceContext.from_defaults(embed_model=embed_model)
>>> from llama_index import Document
>>> index = VectorStoreIndex.from_documents([Document.example()], service_context=service_context)
>>> response = index.as_query_engine().query("Tell me about LLMs")
>>> str(response)
'LLMs are a type of technology that is used for knowledge generation and reasoning. They are pre-trained on large amounts of publicly available data.
```

LlamaIndex has pooling for embeddings actually. We talk the raw output from the model an apply the pooling ourselves (either CLS or mean pooling)
https://github.com/run-llama/llama_index/blob/9672370a2a0c87dee77195f4a518db7b511fc2ed/llama_index/embeddings/huggingface.py#L156

**Comment by logan-markewich** [comment]
Maybe if you share the full error we might better-see the issue?

I noticed this model has an age-old issue, you need to set `max_length=512` in the constructor I think

**Comment by mahmoudben96** [comment]
@logan-markewich Thank you so much for your answer !
Yes, setting `max_length=512` did work for me !
Actually the error happens only when the chunks of the documents had a token length greater than 512. By setting `max_length=512`, tokens longer than 512 get truncated.
